### ISSUE TITLE
Needs a picture

### ISSUE THREAD

**Issue by PiXeL16** [chicus12/resume#1]
Every resume needs a picture, in this case its even more important since Chicus its a very sexy man ❤️ ❤️ ❤️

**Comment by PiXeL16** [comment]
+1

**Comment by chicus12** [comment]
I don't put my photo on my resume because some experts believe that it make your resume illegible, can be distracting and can cause discrimination  (@PiXeL16 i'm not sexy, i'm fluffy). But, thank you for the recommendation.

**Comment by PiXeL16** [comment]
Those "experts" have never seen a real man like Chicus! But fine! Closing the issue
